### ISSUE TITLE
Various compilation error and no task is being exported

### ISSUE THREAD

**Issue by guyzmo** [chris2fr/redmine_taskjuggler#41]
Hello,

I followed the readme in configuring and installing `redmine_taskjuggler`, configured a project to use the module, set it up in `settings`>`information` to have the period covers all the tickets, and then within the `Taskjuggler` tab I do the export. The project is a new project with tasks defined (start/end/dependencies), but no task have been allocated yet. There I get something like the following:

```
project 23 "MyProject" "0.0.0" 2015-01-01 - 2015-12-31  {
  dailyworkinghours 8.0
  extend task {
    number Redmine 'Redmine'
  }
  now 2015-01-12
}
resource mygroup "mygroup" {
resource user1 "User One" {
limits {}
}
resource user2 "User Two" {
limits {}

}
}
flags RedmineIssue

flags team, hidden
account cost "Costs"
account rev "Payments"
include "reports.tji"

taskreport redmine_update_issues_csv_23_0_0_0 'redmine_update_issues_csv_23_0_0_0' {
  formats csv
  hidetask ~RedmineIssue
  columns Redmine, start, end, effort, effortdone, priority
  balance cost rev
}
taskreport redmine_update_issues_html_23_0_0_0 'redmine_update_issues_html_23_0_0_0' {
  formats html
  hidetask ~RedmineIssue
  columns no, name, start, end, effort, effortdone, priority, chart
  balance cost rev
}
```

 - First of all compilation fails because of the project id being inserted after the `project` keyword. If I remove the project id, here it is `23`, that failure is solved ;
 - Then it complains for `reports.tji` not being there. I downloaded the `reports.tji` file from the repository and placed it in the same directory as the downloaded `tjp` file and it compiles ;
 - Finally I get `Error: No tasks defined`, which is obvious as there's actually no tasks being exported within the generated `tjp` file.

I'm currently discovering TaskJuggler and looking how I could integrate it to my workflow, so there may be things I did not understand in its usage…

Thank you for your work!

N.B.: I'm using master's HEAD from your repository, and redmine version 2.5.2.

**Comment by guyzmo** [comment]
ok, for the id the error is that as I'm using easyredmine, I cannot change the project's id which is an automatically generated number. And as the documentation [states][0]: 

> *An identifier is composed of the letters a to z, A to Z, the underscore and the digits 0 to 9. There are no limits for the number of characters, but it may not begin with a digit.*

So I guess a work around would be needed, like adding an underscore if the id of the project starts with a digit… Or maybe ask for a fix in taskjuggler to have it support ids that start with a digit.

[0]:http://www.taskjuggler.org/tj3/manual/index.html

**Comment by guyzmo** [comment]
Ah, I found the log file on the server, which contains:

```
/usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.7.0/lib/bundler/rubygems_integration.rb:256:in `block in replace_gem': taskjuggler is not part of the bundle. Add it to Gemfile. (Gem::LoadError)
	from /usr/local/bin/tj3:22:in `<main>'
```

though, when I run `/usr/local/bin/tj3` from command line, I do not get any error…

**Comment by guyzmo** [comment]
After editing `Gemfile.local` in the root directory of the redmine installation, where I've added `gem "taskjuggler"`, I get rid of that error, but now I'm getting another error: 

```
23-0_0_0.tjp:0: Error: Cannot open file 23-0_0_0.tjp: No such file or directory @ rb_sysopen - 23-0_0_0.tjp
```

which happens upon reload of the `/redmine_taskjuggler_projects/23` path.

**Comment by guyzmo** [comment]
ok, I tried putting the `23-0_0_0.tjp` file I downloaded within the same directory as the log file, and I've done the same fixes as stated in the issue's body, and now I'm getting the same `No tasks defined errors` in the log file. I just do not understand why is it trying to compile upon reload of that webpage? I don't get the workflow here.

**Comment by chris2fr** [comment]
Hey,

Let me get home and we'll see what we can do. Glad you are interested!

Sincerely, Bien cordialement,

Christopher Mann
tel. +33 7 81 811 811

Nota : Email de/from téléphone, with/avec communication ainsi/thus nuancéed.

**Comment by guyzmo** [comment]
well, I still don't exactly know what to expect from taskjuggler, but I'm an avid vim user, I'm a redmine user, and I still need to discover what taskjuggler can bring to me. I'm about to start a project that will need have a very tight schedule for which I'll manage a quite large team, so I'll need to have the best tools at my disposal, and the fastest ways to get updates and do reporting.

**Comment by guyzmo** [comment]
Otherwise, I'm around, and I'm also on IRC/Jabber/whatever if you like instant messaging as well. Oh et je suis francophone aussi ;-)

**Comment by chris2fr** [comment]
Do you have a phone number?

Sincerely, Bien cordialement,

Christopher Mann
tel. +33 7 81 811 811

Nota : Email de/from téléphone, with/avec communication ainsi/thus nuancéed.

**Comment by chris2fr** [comment]
Hi again,

I lost your phone number.

Here is my complete contact info
Christopher MANN
+33 7 81 811 811
christopher@mann.fr

Could you pleas send me an SMS?

I think we may need a working internet connexion, and am not sure what we
can get at Au Pere Tranquille will be fully satisfactory.
It should work with telephone relays.

See you at 2 PM

Christopher

7 place de l'Eglise - 92260 FONTENAY-AUX-ROSES - FRANCE - (prox. Paris)
Mob. +33.7.81.81.18.11 Tel. +33.9.53.33.11.11

2015-01-02 19:38 GMT+01:00 guyzmo <notifications@github.com>:

**Comment by chris2fr** [comment]
Actually, if you have this work on your laptop, please bring it.

**Comment by chris2fr** [comment]
I've just set up my old demo server here
http://redtask.configmagic.com/
but be careful, it is an a very very weak vm and redmine alone can lead to the provider Webfaction.com turning it off.

**Comment by chris2fr** [comment]
Hi,  Did the merge correct the issue?
Your email was put in wiki form here:
https://github.com/chris2fr/redmine_taskjuggler/wiki/Le_Refactoring
